### ISSUE TITLE
Cannot find module 'nodester-cli'

### ISSUE THREAD

**Issue by msprunck** [nodester/nodester-cli#9]
I've installed nodester-cli with npm on macosx. When I try to launch nodester, I get the following error:

mbp:~ matthieu$ nodester

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'nodester-cli'
    at Function._resolveFilename (module.js:299:11)
    at Function._load (module.js:245:25)
    at require (module.js:327:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nodester-cli/0.2.9/package/bin/nodester.js:4:11)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at Array.<anonymous> (module.js:402:10)
    at EventEmitter._tickCallback (node.js:108:26)

When I replace require('nodester-cli') by require('../lib/commands')  in nodester.js it works fine.

**Comment by davglass** [comment]
What version of node? What version of npm?

`node -v`
`npm -v`

**Comment by msprunck** [comment]
node v0.4.2
npm v0.3.15

**Comment by Gnito** [comment]
I had the same problem. (osx 10.6.6, node v0.4.5, npm v0.3.18). 

$ nodester

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'nodester-cli'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nodester-cli/0.2.12/package/bin/nodester.js:4:11)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by msprunck** [comment]
Nodester works with nodejs 0.4.0. I downgraded to nodejs 0.4.0 and now it's working.

**Comment by davglass** [comment]
There is no working difference between 0.4.0 and 0.4.5 (which I have installed on my OSX machine).
